import type { FleetAssumptions } from "@/store/types"

export const defaultFleet: FleetAssumptions = {
  vehicleCount: 750,
  utilizationPercent: 65,
  averageDutyCycleHours: 12,
  annualTruckPlan: [
    { yearIndex: 1, truckCount: 150 },
    { yearIndex: 2, truckCount: 300 },
    { yearIndex: 3, truckCount: 450 },
    { yearIndex: 4, truckCount: 600 },
    { yearIndex: 5, truckCount: 750 },
    { yearIndex: 6, truckCount: 1_000 },
    { yearIndex: 7, truckCount: 1_500 },
    { yearIndex: 8, truckCount: 2_000 },
    { yearIndex: 9, truckCount: 3_000 },
    { yearIndex: 10, truckCount: 5_000 },
  ],
  freightRatePerTonKmUsd: 0.12,
  averagePayloadTons: 28,
  tripsPerTruckPerDay: 1,
  dieselBenchmarkPricePerLiterUsd: 1.15,
  dieselTruckFuelConsumptionLitersPerKm: 0.38,
  truckPurchaseCostUsd: 180_000,
  truckUsefulLifeYears: 8,
  driverCostPerTruckPerYearUsd: 9_000,
  maintenancePerTruckPerYearUsd: 12_000,
  insurancePerTruckPerYearUsd: 4_000,
  tyreCostPerTruckPerYearUsd: 6_500,
  licensingAndPermitsPerTruckPerYearUsd: 2_000,
  adminOverheadUsdPerYear: 300_000,
  taxRatePercent: 30,
  debtSharePercent: 65,
  costOfDebtPercent: 11,
  targetEquityReturnPercent: 22,
}
