import type { PlatformAssumptions } from "@/store/types"

export const defaultPlatform: PlatformAssumptions = {
  corridorName: "A2 E-Corridor",
  stagingPhases: 3,
  goLiveYear: new Date().getFullYear(),
  interoperabilityTier: "baseline",
  corridorDistanceKm: 750,
  staffPerStation: 12,
  staffCostPerPersonPerYearUsd: 7_500,
  cooledWarehouseSizeSqmPerStation: 400,
  stationCapexUsd: 2_500_000,
  swapBayCapexUsd: 350_000,
  chargingSocketCapexUsd: 65_000,
  cooledWarehouseCapexPerSqmUsd: 650,
  softwareDevelopmentCostUsd: 1_250_000,
  softwareMaintenanceCostUsdPerYear: 150_000,
  maintenancePercentInfraCapex: 3,
  insurancePercentAssets: 1.5,
  platformFeeTargetUsdPerKwh: 0.08,
  stationUsefulLifeYears: 25,
  equipmentUsefulLifeYears: 12,
  softwareUsefulLifeYears: 5,
  taxRatePercent: 30,
  debtSharePercent: 60,
  costOfDebtPercent: 9,
  targetEquityReturnPercent: 18,
  adminOverheadUsdPerYear: 250_000,
}
